# Understanding fMRI data

#### This notebook is to take a look at the fMRI data and get an overview of its nature and dimensionality. The aim is to employ some form of neural network based approaches to the data to extract interesting features from it.
---Anshumaan Bajpai



### 1) Importing the key libraries

In [1]:
import os
import numpy as np
from mvpa2.tutorial_suite import *

C:\ProgramData\Anaconda2\lib\site-packages\scipy\integrate\quadpack.py:356: IntegrationWarning: Extremely bad integrand behavior occurs at some points of the
  integration interval.
  warnings.warn(msg, IntegrationWarning)


### 2) Sample datasets

In [5]:
# Simple data
data = [[  1,  1, -1],
        [  2,  0,  0],
        [  3,  1,  1],
        [  4,  0, -1]]

# Converting the data into py-mvpa dataset class
ds = Dataset(data)
print "Shape: ", ds.shape
print "Dataset Length: ",len(ds)
print "Number of features per sample: ", ds.nfeatures
print "Number of samples: "
print ds.samples

Shape:  (4L, 3L)
Dataset Length:  4
Number of features per sample:  3
Number of samples: 
[[ 1  1 -1]
 [ 2  0  0]
 [ 3  1  1]
 [ 4  0 -1]]


In [6]:
# Now we look at a single dimension vector
# A column vector is basically a sample set with one feature each
one_d = [ 0, 1, 2, 3 ]
one_ds = Dataset(one_d)
print "One dimension vector: ", one_ds.shape

One dimension vector:  (4L, 1L)


#### If we have more than 2 dimensions of the dataset, then the second dimension becomes the features and the dimension beyond 2nd becomes the dimensions of each feature

In [8]:
m_ds = Dataset(np.random.random((3, 4, 2, 3)))
print "Shape of Multidimensional dataset: ", m_ds.shape
print "Number of features: ", m_ds.nfeatures
m_ds

Shape of Multidimensional dataset:  (3L, 4L, 2L, 3L)
Number of features:  4


Dataset(array([[[[ 0.86951905,  0.67280464,  0.54327308],
         [ 0.21318062,  0.68254188,  0.85140696]],

        [[ 0.94294783,  0.76368468,  0.41009712],
         [ 0.93492653,  0.48097633,  0.28027629]],

        [[ 0.95608447,  0.48293506,  0.85140577],
         [ 0.96382768,  0.77284312,  0.38017674]],

        [[ 0.3366698 ,  0.50250026,  0.6762115 ],
         [ 0.38722095,  0.60546829,  0.97012871]]],


       [[[ 0.22749869,  0.61474788,  0.99515712],
         [ 0.98840305,  0.94064435,  0.88639495]],

        [[ 0.26553076,  0.29619125,  0.30163137],
         [ 0.11180627,  0.20437163,  0.88806421]],

        [[ 0.32631951,  0.19824717,  0.79880561],
         [ 0.3639337 ,  0.50310994,  0.11523923]],

        [[ 0.69904645,  0.45991945,  0.07912541],
         [ 0.36155155,  0.33168133,  0.29656911]]],


       [[[ 0.98165581,  0.15642412,  0.7150341 ],
         [ 0.98623699,  0.17413419,  0.63249755]],

        [[ 0.59906721,  0.96657221,  0.61361701],
         [ 0.7207437

#### In the above, we have a 3 sample point with 4 features each. Each feature is a 2 by 3 matrix